#! /bin/sh
xset -b

#Misc keyboard stuff, since keyboards are stupid and my hands are worse
setxkbmap -option caps:backspace
xmodmap -e "keycode 105 = Escape" #rctrl
xmodmap -e "keycode 108 = Escape" #alt-gr

sxhkd &

bspc config remove_disabled_monitors true
xrandr --output HDM1 --primary --mode 1920x1080
xrandr --output LVDS1 --off
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config bottom_padding 	 25 #change for standby/battle mode?
bspc config top_padding 	 0
bspc config right_padding	 0
bspc config left_padding 	 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true

bspc config click_to_focus	 true

sh /home/sourec/Dotfiles/modes/switch_standby.sh
