#! /bin/sh
xset -b

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config bottom_padding 	 19 #change for standby/battle mode?
bspc config top_padding 	 5
bspc config right_padding	 5
bspc config left_padding 	 5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true

bspc config click_to_focus	 true



sh /home/sourec/Dotfiles/modes/switch_standby.sh
