#!/bin/sh

# This file is run when BSPWM starts, or when the display
# manager (SLIM) launches it. Consequently, it's a good
# place for a whole lot of init stuff.
compton --config .config/compton/compton.conf -b
xsetroot -cursor_name left_ptr	# why won't this run in xinitrc...?
~/dotfiles/scripts/setwallpaper.sh
~/dotfiles/polybar/polylaunch.sh &
xset -b
conky &

# Keyboard settings
setxkbmap -option caps:backspace 	# one of the best things about colmaks (sp?) 
xset r 66				# repeat capslock backspace
xmodmap -e "keycode 248 = Alt_L"	# g12->alt_l
xmodmap -e "keycode 174 = Alt_L"
xmodmap -e "keycode 108 = Escape"

# Monitor stuff
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

# Layoutish stuff
bspc config border_width		3
bspc config window_gap			5
bspc config bottom_padding		0
bspc config top_padding			32
bspc config right_padding		0
bspc config left_padding		0
bspc config split_ratio			0.5

# Mouse?
bspc config click_to_focus		true

# Appearance
bspc config normal_border_color		'#555555'	# light grey
bspc config focused_border_color	'#CCCCCC'	# tinged white
bspc config active_border_color		'#B3EOEO'	# tinged light cyan
bspc config presel_feedback_color	'#FFFFFF'	# white
bspc config borderless_monocle		true
bspc config gapless_monocle		true

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=on
termite --class scratchpad -e ~/dotfiles/bspwm/scratchpad &

# Misc
bspc history_aware_focus	true
wmname LG3D # Some things don't work without this

# Rules
bspc rule -a conky border=false
bspc rule -a TelegramDesktop desktop=VIII
bspc rule -a discord desktop=VIII
bspc rule -a KeePass2 desktop=X
bspc rule -a Thunderbird desktop=IX
bspc rule -a Slack desktop=VII

# Autostart a few routine programs.
telegram-desktop &
thunderbird & 		# this can't possibly end badly, can it?
slack &
discord &
