[dotrix.link]
"dotfiles/media/wallpaper-base" = "wallpapers/kobayashi-maru-solarized.png"
"dotfiles/media/lockscreen.png" = "lockscreens/hal-transparent.png"

[dotrix]
ignore = [ "lockscreen.png", "wallpaper-base", "wallpapers", "lockscreens", "sounds" ]
