[dotrix.link]
"dotfiles/media/wallpaper-base.png" = "wallpapers/solar.png"
"dotfiles/media/lockscreen.png" = "lockscreens/hal-transparent.png"

[dotrix]
ignore = [ "lockscreen.png", "wallpaper-base.png", "wallpapers", "lockscreens",
		"sounds" ]
