[dotrix.link]
".local/share/fonts/Bank-Gothic.ttf" = "Bank-Gothic.ttf"
".local/share/fonts/Inconsolata-Regular.ttf" = "Inconsolata-Regular.ttf"
".local/share/fonts/Inconsolata-Bold.ttf" = "Inconsolata-Bold.ttf"
".local/share/fonts/Inconsolata-Powerline.otf" = "Inconsolata-Powerline.otf"
