#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

#From a helpful user on CrunchBang
#http://crunchbang.org/forums/viewtopic.php?id=36291

import sys
from subprocess import check_output
from xml.dom.minidom import parseString

try:
	tagname = sys.argv[1]
	data = check_output(["curl", "-s", "-u", ":vlcpassword", "http://127.0.0.1:8080/requests/status.xml"], shell=False)
	dom = parseString(data)
	elements = dom.getElementsByTagName(tagname)
	xmlData = "undefined"
	if len(sys.argv) == 2:
		xmlTag = elements[0].toxml()
		xmlData = xmlTag.replace('<' + tagname + '>', '').replace('</' + tagname + '>', '')
		if sys.argv[1] == "position":
			xmlData = int(0.5 + float(xmlData) * 100.0)
	else:
		for i in range(0, len(elements) - 1):
			xmlTag = elements[i].toxml()
			if "name=\"" + sys.argv[2] in xmlTag:
				xmlData = xmlTag.replace('<' + tagname + ' name=\"' + sys.argv[2] + '\">', '').replace('</' + tagname + '>', '')
	print xmlData
except:
	print "error"
